# Generated by Django 2.2.3 on 2019-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_sentiment_contrarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_sentiment_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_spread',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='perdiction_accuracy',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_charge_hight',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_charge_low',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profit_limit',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='size',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='stop_limit',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_client_sentiment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='watermark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
