# Generated by Django 2.2.3 on 2019-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190716_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_spread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perdiction_accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profit_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stop_limit',
            field=models.IntegerField(default=0),
        ),
    ]
