# Generated by Django 2.2.3 on 2019-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190716_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price_charge_hight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price_charge_low',
            field=models.IntegerField(default=0),
        ),
    ]
