# Generated by Django 2.2.3 on 2019-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190716_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_spread',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perdiction_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price_charge_hight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price_charge_low',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profit_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stop_limit',
            field=models.FloatField(default=0),
        ),
    ]
