# Generated by Django 2.2.3 on 2019-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190717_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client_sentiment_contrarian',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='use_client_sentiment',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=1),
        ),
    ]
