# Generated by Django 2.2.3 on 2019-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190717_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.CharField(choices=[('1', 'Invest IQ Premium Signals'), ('2', 'Invest IQ Automated Trading'), ('3', 'Invest IQ Managed Service')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
